export const ApplicationExceptionName = {
    NOT_FOUND: "NOT_FOUND",
    NOT_BELONGS_TO: "NOT_BELONGS_TO",
    TYPE_MISMATCH: "TYPE_MISMATCH",
    BUSINESS_RULE_VIOLATION: "BUSINESS_RULE_VIOLATION",
    INVALID_OPERATION: "INVALID_OPERATION",
}