enum ApiExceptionNameEnum {
    EXPIRED_TOKEN = "EXPIRED_TOKEN",
    UNAUTHENTICATED_USER = "UNAUTHENTICATED_USER",
    PAYLOAD_VALIDATION_EXCEPTION = "PAYLOAD_VALIDATION_EXCEPTION"
}
export default ApiExceptionNameEnum